package cc.moecraft.irc.osubot.database.model;

import cc.moecraft.irc.osubot.database.model.base.BaseOsuCtb;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_ctb", primaryKey = "user_id")
public class OsuCtb extends BaseOsuCtb<OsuCtb> {
	
}
