package cc.moecraft.irc.osubot.database.model;

import io.jboot.db.annotation.Table;
import cc.moecraft.irc.osubot.database.model.base.BaseOsuLua;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_lua", primaryKey = "user_id")
public class OsuLua extends BaseOsuLua<OsuLua> {
	
}
