package cc.moecraft.irc.osubot.database.model;

import cc.moecraft.irc.osubot.database.model.base.BaseOsuMania;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_mania", primaryKey = "user_id")
public class OsuMania extends BaseOsuMania<OsuMania> {
	
}
