package cc.moecraft.irc.osubot.database.model;

import cc.moecraft.irc.osubot.database.model.base.BaseOsuStd;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_std", primaryKey = "user_id")
public class OsuStd extends BaseOsuStd<OsuStd> {
	
}
