package cc.moecraft.irc.osubot.database.model;

import cc.moecraft.irc.osubot.database.model.base.BaseOsuTaiko;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_taiko", primaryKey = "user_id")
public class OsuTaiko extends BaseOsuTaiko<OsuTaiko> {
	
}
