package cc.moecraft.irc.osubot.database.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOsuLua<M extends BaseOsuLua<M>> extends JbootModel<M> implements IBean {

    public static final String ACTION_ADD = "OsuLua:add";
    public static final String ACTION_DELETE = "OsuLua:delete";
    public static final String ACTION_UPDATE = "OsuLua:update";


    @Override
    public String addAction() {
        return ACTION_ADD;
    }

    @Override
    public String deleteAction() {
        return ACTION_DELETE;
    }

    @Override
    public String updateAction() {
        return ACTION_UPDATE;
    }


	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}
	
	public java.lang.String getLanguage() {
		return getStr("language");
	}

}
