ServerProperties:
  Address: localhost
  Port: 6667
AccountProperties:
  Username: HyOsuBot
  Password: ''
BotProperties:
  AdminUsernames:
  - Hykilpikonna
  - dullwolf
  CommandPrefix: '!'
  AutoJoinChannels:
  - '#general'
  - '#chinese'
DefaultConfig: false
ConfigVersion: 0.0.1
