package cc.moecraft.irc.osubot.osu;


public enum Api
{

    User          ("https://osu.ppy.sh/api/get_user"),
    Score         ("https://osu.ppy.sh/api/get_scores"),
    Recent        ("https://osu.ppy.sh/api/get_user_recent");

    public static final double[] PP_SCALE = new double[]
            {
                    1,
                    .95,
                    .9,
                    .86,
                    .81,
                    .77,
                    .74,
                    .7,
                    .66,
                    .63,
                    .6,
                    .57,
                    .54,
                    .51,
                    .49,
                    .46,
                    .44,
                    .42,
                    .40,
                    .38,
                    .34,
                    .32,
                    .31,
                    .29,
                    .28,
                    .26,
                    .25,
                    .24,
                    .22,
                    .21,
                    .20,
                    .19,
                    .18,
                    .17,
                    .17,
                    .16,
                    .15,
                    .14,
                    .14,
                    .13,
                    .12,
                    .12,
                    .11,
                    .10,
                    .20,
                    .9,
                    .9,
                    .9,
                    .8,
                    .8,
                    .7,
                    .7,
                    .7,
                    .6,
                    .6,
                    .6,
                    .5,
                    .5,
                    .5,
                    .5,
                    .4,
                    .4,
                    .4,
                    .4,
                    .4,
                    .3,
                    .3,
                    .3,
                    .3,
                    .3,
                    .3,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .2,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1,
                    .1
            };

    public String apiUrl;

    Api(String value)
    {
        this.apiUrl = value;
    }
}
