package cc.moecraft.irc.osubot.model;

import io.jboot.db.annotation.Table;
import cc.moecraft.irc.osubot.model.base.BaseOsu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu", primaryKey = "id")
public class Osu extends BaseOsu<Osu> {
	
}
