package cc.moecraft.irc.osubot.model;

import io.jboot.db.annotation.Table;
import cc.moecraft.irc.osubot.model.base.BaseOsuStd;

/**
 * Generated by Jboot.
 */
@Table(tableName = "osu_std", primaryKey = "user_id")
public class OsuStd extends BaseOsuStd<OsuStd> {
	
}
